language: node_js
node_js:
- '4'
- '6'
- '8'
- '9'
script:
- FUZZY_AI_KEY=$FUZZY_AI_KEY npm test
deploy:
  provider: npm
  api_key:
    secure: 3zdxdJT2U5pCsQnRi6iUDk22Lc8JU58ix5smG1+FD0MOb9XHjbKwYUB9iHipJ6lCPITEPCNNy8x2cPYFtEPcOe+zdDWacT/0i2lXl/sHsQy3O8wK8Rc3HQLGdlSTMyIewwtewcNodSlIz6KVGCbEUv6aiYBTZjpgwcMkD0EpXZmXYbNOEvqxJ9lFKhxSd3zHTYP9d2TQGiICpTOnF/X9BtkY/Kfg2XRaziaAFSJCjcj2e50LfAhZSUZHMpQw120DjG4zoWsFwzGZpLNImYYuVM40Qp40jlmua8nqf50mpnqt7OhVgsg4x0H9VvxyBi3knrEIHSY5f1QkLwEf0Tec6AKTMoOy6LcrXHJV7tT9LG/yZ+YB2tMdci46auPylcbxyf4dQYXEx5wEFluscvgDwHnDa59ps/cKuamz5tYCH0NA7eIYM0/T83pZNuPt6qyCfUJUm9PCXQsTRYOpBCKILLwXZ4zglOgNY3vUMXhjA95ABTJtYh4+XtnvrEtujb7elZeFYle/zB9i1mzmbWBMUYlSedLGpfuPQf1w1eh2AsHu6tgjZecdGROC067ZEurs3IHu4DaUVXLA3drCnQ7Ha96ZuQ1n725G4NpmQ/WNDy0d+zAGtuRWyIZ83vlC4zqd/CcnmZVvDks+AMhaJse6ru5HM0+hs9pnR07f2DghZOg=
  on:
    tags: true
env:
  global:
    secure: xyGc/iR+bmCcCxWYGSkm6CmFVAuQGn2INHb9xUv8eyx1Ow+6vWcg2JN2ahtV1MPCc/02HWYCktjdq4ySLMaIkhGQB22lIpHdb/7NidYvHzJREGLZOyZyRITMAjap5wslERvKrgfEuOFMhGAUkabSpJo+cXuHAfqpgav05o0SRbM5pRIT5sMdyhWXJH/RCazf+nRpyMXlW/8F5qffbbUAzYEq7ypag7vAHtIXOpZlEcsP0Vzc01Ets1tgHSjFmvTUUzFrytQWBoigo+DBXKbp77jAWCu93XFX7ZHfoht/EZlrIx2mJ/e0XW5RCTbVd8BRG8Kad34tHuQuYHdxN4F9wYFnvQBsvBWnqkM7WF38z9tDNgxkVI1+Avqul0mUIfaBsHTogXWr0iGBJnk/3udyo6m3kLGMTGlDu9fpG5NJA0+7m2b3ppTxt6PqtJXfVmYzt2oSn201uEfQm1gq4t4Gqc+0iKFGJAtOwQprAuerARFYe4i4l6T6WdLlo4SLYqQQErOhtxpSDe/9Fhml9NpAqfD+ZHikkcKVVX75TpRHzAECiAwCmtFAQI70Tphfot2P57j1Kdm5t5j9HKvubaHZq+mNEgScOmwIxLc7PxKFSFxWx391cFxiURLfd5f+HxTozIRLsYx895jf2J/wQLk5QuJBcDC8PEp0BXM4Lk0s7PE=
